# Generated by Django 4.2.5 on 2024-03-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trees_database',
            table='trees_database',
        ),
    ]
