# Generated by Django 5.0.4 on 2024-04-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_comment_options_rename_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='myapp_comme_created_f2e527_idx',
        ),
    ]
