# Generated by Django 5.0.4 on 2024-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_comment_myapp_comme_created_f2e527_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
